package me.bristermitten.mittenlib.annotations.compile

import com.palantir.javapoet.{ClassName, CodeBlock, MethodSpec}
import me.bristermitten.mittenlib.annotations.ast.{AbstractConfigStructure, ConfigTypeSource, Property}
import org.jspecify.annotations.Nullable
import javax.lang.model.element.TypeElement
import javax.lang.model.`type`.TypeMirror

object GeneratorUtil:

  def getDaoName(
    ast: AbstractConfigStructure,
    classNameGenerator: ConfigurationClassNameGenerator
  ): ClassName =
    ast.source() match {
      case _: ConfigTypeSource.InterfaceConfigTypeSource => classNameGenerator.getInnerDaoName(ast)
      case _: ConfigTypeSource.ClassConfigTypeSource => ast.name()
    }

  def addDaoInstantiationIfNecessary(
    ast: AbstractConfigStructure,
    methodBuilder: MethodSpec.Builder,
    @Nullable daoName: ClassName
  ): Unit =
    val hasAnyDefault = ast.properties().stream().anyMatch(p => p.settings().hasDefaultValue())
    if (daoName != null && hasAnyDefault) {
      methodBuilder.addStatement("$T dao = new $T()", daoName, daoName)
    }

  def getPropertyAccess(
    ast: AbstractConfigStructure,
    property: Property,
    configExpr: me.bristermitten.mittenlib.codegen.dsl.Expr,
    methodNames: MethodNames,
    useGetters: Boolean
  ): me.bristermitten.mittenlib.codegen.dsl.Expr =
    ast.source() match {
      case _: ConfigTypeSource.InterfaceConfigTypeSource =>
        configExpr.call(property.name())
      case _: ConfigTypeSource.ClassConfigTypeSource =>
        if (useGetters) {
          configExpr.call(methodNames.safeMethodName(property))
        } else {
          configExpr.field(property.name())
        }
    }

  def declareAndCheckFromMap(
    propertyAST: AbstractConfigStructure,
    property: Property,
    dtoType: TypeElement,
    elementType: TypeMirror,
    context: me.bristermitten.mittenlib.codegen.dsl.StagedExpr[me.bristermitten.mittenlib.config.DeserializationContext],
    hasDefault: Boolean,
    dao: Option[me.bristermitten.mittenlib.codegen.dsl.StagedExpr[Any]],
    fieldNameGenerator: FieldNameGenerator
  )(using me.bristermitten.mittenlib.codegen.dsl.BlockBuilder): me.bristermitten.mittenlib.codegen.dsl.Var =
    import me.bristermitten.mittenlib.codegen.dsl.*
    import me.bristermitten.mittenlib.codegen.dsl.BlockBuilder.*
    import me.bristermitten.mittenlib.codegen.dsl.given
    import com.palantir.javapoet.TypeName
    import me.bristermitten.mittenlib.config.exception.ConfigLoadingErrors

    val data = declare(Types.DataTree, "$data", context.getData)
    val key = fieldNameGenerator.getConfigFieldName(property)
    val fromMapName = property.name() + "FromMap"

    val fromMap = if (hasDefault) {
      val defaultAccess = propertyAST.source() match {
        case source: ConfigTypeSource.ClassConfigTypeSource => dao.get.field(property.name())
        case source: ConfigTypeSource.InterfaceConfigTypeSource => dao.get.call(property.name())
      }
      declare(Types.Object, fromMapName, data.call("getOrDefault", Expr.str(key), defaultAccess))
    } else {
      declare(Types.DataTree, fromMapName, data.call("get", Expr.str(key)))
    }

    if (property.settings().isNullable()) {
      ifThen(fromMap.isNull) {
        return_(ResultExpr.ok(Expr.Null))
      }
    } else {
      ifThen(fromMap.isNull) {
        return_(
          ResultExpr.fail(
            Expr.staticCall(TypeRef.of(classOf[ConfigLoadingErrors]), "notFoundException",
              Expr.str(property.name()),
              Expr.str(TypeName.get(elementType).withoutAnnotations().toString),
              Expr.staticField(TypeRef.of(dtoType), "class"),
              Expr.str(key)
            )
          )
        )
      }
    }
    fromMap

  def generatedAnnotation(includeDate: Boolean = false): com.palantir.javapoet.AnnotationSpec =
    import com.palantir.javapoet.AnnotationSpec
    import java.time.ZoneId
    import java.time.ZonedDateTime
    import java.time.format.DateTimeFormatter
    import javax.annotation.processing.Generated
    import me.bristermitten.mittenlib.annotations.config.ConfigProcessor

    val builder = AnnotationSpec.builder(classOf[Generated])
      .addMember("value", "$S", classOf[ConfigProcessor].getName)
      .addMember("comments", "$S", "Generated by MittenLib Annotation Processor")

    if (includeDate) {
      builder.addMember(
        "date", "$S", ZonedDateTime.now(ZoneId.systemDefault()).format(DateTimeFormatter.ISO_INSTANT)
      )
    }
    builder.build()
