[versions]
spigot = "1.8.8-R0.1-SNAPSHOT"
guice = "6.0.0"
auto-service = "1.0.1"
adventure-api = "4.11.0"
adventure-platform = "4.1.2"
junit = "5.8.1"
assertj = "3.27.3"
mockito = "4.8.0"
aptk = "0.22.5"

# Plugins
freefair = "9.5.0"
errorprone-plugin = "5.1.0"
spotbugs-plugin = "6.5.5"
spotless-plugin = "8.6.0"
githook-plugin = "1.2.1"

[libraries]
spotless-gradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless-plugin" }
spotbugs-gradle = { group = "com.github.spotbugs.snom", name = "spotbugs-gradle-plugin", version.ref = "spotbugs-plugin" }
githook-gradle = { group = "com.star-zero.gradle.githook", name = "com.star-zero.gradle.githook.gradle.plugin", version.ref = "githook-plugin"}
errorprone-gradle = { group = "net.ltgt.gradle", name = "gradle-errorprone-plugin", version.ref = "errorprone-plugin" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }
auto-service-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "auto-service" }
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
jimfs = { group = "com.google.jimfs", name = "jimfs", version = "1.2" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.11.0" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version = "2.18.2" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version = "2.3" }
compile-testing = { group = "com.google.testing.compile", name = "compile-testing", version = "0.19" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure-api" }
adventure-platform-bukkit = { group = "net.kyori", name = "adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version = "4.10.1" }

junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" } # withoutVersion

assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }
mockbukkit = { group = "com.github.bristermitten", name = "MockBukkit", version = "93122b01fcbb3f66b211aede5eb66000e78b117f" }

javapoet = { group = "com.squareup", name = "javapoet", version = "1.13.0" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "23.0.0" }
jspecify = { group = "org.jspecify", name = "jspecify", version = "1.0.0" }
acf-paper = { group = "co.aikar", name = "acf-paper", version = "0.5.1-SNAPSHOT" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version = "2.11.6" }

aptk-tools = { group = "io.toolisticon.aptk", name = "aptk-tools", version.ref = "aptk" }
aptk-compilermessages-api = { group = "io.toolisticon.aptk", name = "aptk-compilermessages-api", version.ref = "aptk" }
aptk-compilermessages-processor = { group = "io.toolisticon.aptk", name = "aptk-compilermessages-processor", version.ref = "aptk" }
aptk-annotationwrapper-processor = { group = "io.toolisticon.aptk", name = "aptk-annotationwrapper-processor", version.ref = "aptk" }
aptk-annotationwrapper-api = { group = "io.toolisticon.aptk", name = "aptk-annotationwrapper-api", version.ref = "aptk" }

cute = { group = "io.toolisticon.cute", name = "cute", version = "1.9.0" }
chalk = { group = "com.github.tomas-langer", name = "chalk", version = "1.0.2" }

errorprone = { group = "com.google.errorprone", name = "error_prone_core", version = "2.26.1" }

[bundles]
autoservice = ["auto-service-annotations", "auto-service"]

[plugins]
freefair-aggregate-javadoc = { id = "io.freefair.aggregate-javadoc", version.ref = "freefair" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs-plugin" }
