package me.bristermitten.mittenlib.config;

import org.jspecify.annotations.Nullable;

/**
 * Represents a loadable configuration from a file which will (de)serialize to/from an object of type {@link T}.
 *
 * @param <T> the type of the config's abstract representation.
 */
public class Configuration<T> {
    private final @Nullable String fileName;
    private final Class<T> type;

    private final Class<?> implementationType;

    /**
     * Create a new Configuration
     *
     * @param fileName the name of the file to load
     * @param type     the type to deserialize to
     */
    public Configuration(@Nullable String fileName, Class<T> type, Class<?> implementationType) {
        this.fileName = fileName;
        this.type = type;
        this.implementationType = implementationType;
    }

    /**
     * Create a new Configuration
     *
     * @param fileName the name of the file to load
     * @param type     the type to deserialize to
     * @deprecated Use {@link #Configuration(String, Class, Class)} to provide the implementation type for better error messages
     */
    @Deprecated
    public Configuration(@Nullable String fileName, Class<T> type) {
        this(fileName, type, type);
    }

    public @Nullable String getFileName() {
        return fileName;
    }

    /**
     * Returns the type to deserialize to.
     *
     * @return the type to deserialize to
     */
    public Class<T> getType() {
        return type;
    }

    /**
     * Get the concrete implementation type of this configuration.
     * This may be the same as {@link #getType()}, but if the configuration was generated by the annotation processor,
     * it will be the actual generated implementation class, as opposed to {@link #getType()} which is the original DTO type.
     */
    public Class<?> getImplementationType() {
        return implementationType;
    }
}
