package me.bristermitten.mittenlib.annotations.compile;

import com.google.inject.Inject;
import com.google.inject.Provider;
import com.squareup.javapoet.*;
import io.toolisticon.aptk.tools.TypeMirrorWrapper;
import me.bristermitten.mittenlib.annotations.ast.AbstractConfigStructure;
import me.bristermitten.mittenlib.annotations.ast.Property;
import me.bristermitten.mittenlib.annotations.config.ConfigProcessor;
import me.bristermitten.mittenlib.annotations.parser.CustomSerializers;
import me.bristermitten.mittenlib.annotations.util.TypesUtil;
import me.bristermitten.mittenlib.config.SerializationContext;
import me.bristermitten.mittenlib.config.SerializationFunction;
import me.bristermitten.mittenlib.config.tree.DataTree;
import me.bristermitten.mittenlib.config.tree.DataTreeTransforms;
import me.bristermitten.mittenlib.util.Strings;

import javax.annotation.processing.Generated;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class ConfigSaverGenerator {
    private final ConfigurationClassNameGenerator classNameGenerator;
    private final SerializationCodeGenerator serializationCodeGenerator;
    private final MethodNames methodNames;
    private final TypesUtil typesUtil;
    private final FieldNameGenerator fieldNameGenerator;
    private final ConfigNameCache configNameCache;
    private final CustomSerializers customSerializers;

    @Inject
    public ConfigSaverGenerator(
            ConfigurationClassNameGenerator classNameGenerator,
            SerializationCodeGenerator serializationCodeGenerator,
            MethodNames methodNames,
            TypesUtil typesUtil,
            FieldNameGenerator fieldNameGenerator,
            ConfigNameCache configNameCache,
            CustomSerializers customSerializers) {
        this.classNameGenerator = classNameGenerator;
        this.serializationCodeGenerator = serializationCodeGenerator;
        this.methodNames = methodNames;
        this.typesUtil = typesUtil;
        this.fieldNameGenerator = fieldNameGenerator;
        this.configNameCache = configNameCache;
        this.customSerializers = customSerializers;
    }

    /**
     * Entry point for generating a {@link JavaFile} for a configuration saver.
     *
     * @param ast the configuration structure to generate a saver for
     * @return a {@link JavaFile} containing the generated saver class
     */
    public JavaFile emit(AbstractConfigStructure ast) {
        ClassName saverClassName = classNameGenerator.getSerializerClassName(ast);
        TypeSpec.Builder builder = createSaverBuilder(ast);

        return JavaFile.builder(saverClassName.packageName(), builder.build()).build();
    }

    /**
     * Creates the {@link TypeSpec.Builder} for the saver class, including its annotations,
     * constructor, fields, and serialization methods.
     *
     * @param ast the configuration structure
     * @return a builder for the saver class
     */
    private TypeSpec.Builder createSaverBuilder(AbstractConfigStructure ast) {
        ClassName publicClassName = classNameGenerator.getPublicClassName(ast);
        ClassName saverClassName = classNameGenerator.getSerializerClassName(ast);

        TypeSpec.Builder builder =
                TypeSpec.classBuilder(saverClassName)
                        .addModifiers(Modifier.PUBLIC)
                        .addSuperinterface(
                                ParameterizedTypeName.get(
                                        ClassName.get(SerializationFunction.class), publicClassName));

        // Add @Generated annotation
        builder.addAnnotation(
                AnnotationSpec.builder(Generated.class)
                        .addMember("value", "$S", ConfigProcessor.class.getName())
                        .addMember("comments", "$S", "Generated by MittenLib Annotation Processor")
                        .addMember(
                                "date",
                                "$S",
                                ZonedDateTime.now(ZoneId.systemDefault()).format(DateTimeFormatter.ISO_INSTANT))
                        .build());

        MethodSpec.Builder constructorBuilder =
                MethodSpec.constructorBuilder().addAnnotation(Inject.class).addModifiers(Modifier.PUBLIC);

        // Add child savers as dependencies recursively
        for (Property property : ast.properties()) {
            collectSaverDependencies(property.propertyType(), builder, constructorBuilder);
        }

        // Add custom serializers as dependencies recursively
        Set<TypeName> injectedTypes = new LinkedHashSet<>();
        Map<TypeName, String> injectedFieldNames = new LinkedHashMap<>();
        for (Property property : ast.properties()) {
            collectCustomSerializers(property.propertyType(), injectedTypes, injectedFieldNames);
        }

        for (TypeName typeName : injectedTypes) {
            String fieldName = injectedFieldNames.get(typeName);
            TypeName providerType = ParameterizedTypeName.get(ClassName.get(Provider.class), typeName);
            builder.addField(
                    FieldSpec.builder(providerType, fieldName, Modifier.PRIVATE, Modifier.FINAL).build());
            constructorBuilder.addParameter(providerType, fieldName);
            constructorBuilder.addStatement("this.$L = $L", fieldName, fieldName);
        }

        builder.addMethod(constructorBuilder.build());

        // Implement apply method
        MethodSpec.Builder applyMethod =
                MethodSpec.methodBuilder("apply")
                        .addAnnotation(Override.class)
                        .addModifiers(Modifier.PUBLIC)
                        .returns(DataTree.class)
                        .addParameter(publicClassName, "config")
                        .addParameter(SerializationContext.class, "context");

        applyMethod.addStatement(
                "$T<$T, $T> map = new $T<>()",
                Map.class,
                DataTree.class,
                DataTree.class,
                LinkedHashMap.class);

        for (Property property : ast.properties()) {
            String key = fieldNameGenerator.getConfigFieldName(property);
            String serializeMethodName = methodNames.getSerializeMethodName(property);

            // Get the property value based on source type
            CodeBlock propertyAccess =
                    GeneratorUtil.getPropertyAccess(ast, property, "config", methodNames, true);

            applyMethod.addStatement(
                    "map.put($T.string($S), this.$L($L, context))",
                    DataTree.class,
                    key,
                    serializeMethodName,
                    propertyAccess);
        }

        applyMethod.addStatement("return $T.map(map)", DataTree.class);
        builder.addMethod(applyMethod.build());

        addGenerateDefaultMethod(ast, builder);

        // Add private serialize methods for each property (copied from SerializationCodeGenerator but
        // adapted)
        serializationCodeGenerator.addSerializeMethodsToSaver(builder, ast);

        // Add nested classes
        for (AbstractConfigStructure enclosed : ast.enclosed()) {
            builder.addType(createSaverBuilder(enclosed).addModifiers(Modifier.STATIC).build());
        }

        return builder;
    }

    /**
     * Adds the {@code generateDefault} method to the saver, which creates a default {@link DataTree}
     * for the configuration structure, using a DAO for default values when possible.
     *
     * <p>Generates:
     *
     * <pre>{@code
     * public DataTree generateDefault(SerializationContext context) {
     *     MyConfigDAO dao = new MyConfigDAO(); // DAO is either the DefaultMethodAccess or original Config class
     *     Map<DataTree, DataTree> map = new LinkedHashMap<>();
     *     map.put(DataTree.string("count"), this.serializeCount(dao.getCount(), context));
     *     return DataTree.map(map);
     * }
     * }</pre>
     *
     * @param ast     the configuration structure, used to determine the properties to include in the
     *                default tree
     * @param builder the saver class builder
     */
    private void addGenerateDefaultMethod(AbstractConfigStructure ast, TypeSpec.Builder builder) {
        MethodSpec.Builder method =
                MethodSpec.methodBuilder("generateDefault")
                        .addAnnotation(Override.class)
                        .addModifiers(Modifier.PUBLIC)
                        .returns(DataTree.class)
                        .addParameter(SerializationContext.class, "context");

        ClassName daoName = GeneratorUtil.getDaoName(ast, classNameGenerator);
        GeneratorUtil.addDaoInstantiationIfNecessary(ast, method, daoName);

        method.addStatement(
                "$T<$T, $T> map = new $T<>()",
                Map.class,
                DataTree.class,
                DataTree.class,
                LinkedHashMap.class);

        for (Property property : ast.properties()) {
            String key = fieldNameGenerator.getConfigFieldName(property);
            if (property.settings().hasDefaultValue()) {
                TypeMirror propertyType = property.propertyType();
                if (typesUtil.isConfigType(propertyType)
                        || TypeMirrorWrapper.wrap(propertyType).hasTypeArguments()) {
                    // For nested configs or generic collections with defaults, use the mapper
                    CodeBlock propertyAccess =
                            GeneratorUtil.getPropertyAccess(ast, property, "dao", methodNames, false);
                    method.addStatement(
                            "map.put($T.string($S), $T.loadFrom(context.getMapper().map($L)))",
                            DataTree.class,
                            key,
                            DataTreeTransforms.class,
                            propertyAccess);
                } else {
                    String serializeMethodName = methodNames.getSerializeMethodName(property);
                    CodeBlock propertyAccess =
                            GeneratorUtil.getPropertyAccess(ast, property, "dao", methodNames, false);
                    method.addStatement(
                            "map.put($T.string($S), this.$L($L, context))",
                            DataTree.class,
                            key,
                            serializeMethodName,
                            propertyAccess);
                }
            } else if (typesUtil.isConfigType(property.propertyType())) {
                if (property.settings().isNullable()) {
                    method.addStatement(
                            "map.put($T.string($S), $T.null_())", DataTree.class, key, DataTree.class);
                } else {
                    String saverFieldName =
                            classNameGenerator.getSerializerProviderFieldName(property.propertyType());
                    method.addStatement(
                            "map.put($T.string($S), this.$L.get().generateDefault(context))",
                            DataTree.class,
                            key,
                            saverFieldName);
                }
            } else {
                TypeMirrorWrapper wrapped = TypeMirrorWrapper.wrap(property.propertyType());
                if (wrapped.hasTypeArguments()) {
                    String canonicalName = wrapped.erasure().getQualifiedName();
                    if (canonicalName.equals(List.class.getName())) {
                        method.addStatement(
                                "map.put($T.string($S), $T.array())", DataTree.class, key, DataTree.class);
                    } else if (canonicalName.equals(Map.class.getName())) {
                        method.addStatement(
                                "map.put($T.string($S), $T.map($T.emptyMap()))",
                                DataTree.class,
                                key,
                                DataTree.class,
                                Collections.class);
                    } else {
                        method.addStatement(
                                "map.put($T.string($S), $T.null_())", DataTree.class, key, DataTree.class);
                    }
                } else {
                    method.addStatement(
                            "map.put($T.string($S), $T.null_())", DataTree.class, key, DataTree.class);
                }
            }
        }

        method.addStatement("return $T.map(map)", DataTree.class);
        builder.addMethod(method.build());
    }

    /**
     * Adds a dependency on another configuration saver to the class fields and constructor.
     *
     * <p>Generates:
     *
     * <pre>{@code
     * private final Provider<SerializationFunction<OtherConfig>> otherConfigSaver;
     *
     * @Inject
     * public MyConfigSaver(Provider<SerializationFunction<OtherConfig>> otherConfigSaver) {
     *     this.otherConfigSaver = otherConfigSaver;
     * }
     * }</pre>
     *
     * @param builder            the saver class builder
     * @param constructorBuilder the constructor builder
     * @param type               the type of the configuration whose saver is needed (e.g. {@code OtherConfig})
     */
    private void addSaverDependency(
            TypeSpec.Builder builder, MethodSpec.Builder constructorBuilder, TypeMirror type) {
        AbstractConfigStructure ast = configNameCache.lookupAST(type).orElse(null);
        if (ast == null) return;

        ClassName publicChildClassName = classNameGenerator.getPublicClassName(ast);
        String fieldName = classNameGenerator.getSerializerProviderFieldName(type);

        if (builder.fieldSpecs.stream().anyMatch(f -> f.name.equals(fieldName))) {
            return;
        }

        builder.addField(
                ParameterizedTypeName.get(
                        ClassName.get(Provider.class),
                        ParameterizedTypeName.get(
                                ClassName.get(SerializationFunction.class), publicChildClassName)),
                fieldName,
                Modifier.PRIVATE,
                Modifier.FINAL);

        constructorBuilder.addParameter(
                ParameterizedTypeName.get(
                        ClassName.get(Provider.class),
                        ParameterizedTypeName.get(
                                ClassName.get(SerializationFunction.class), publicChildClassName)),
                fieldName);
        constructorBuilder.addStatement("this.$L = $L", fieldName, fieldName);
    }

    /**
     * Recursively traverses generic type arguments of a property's type to discover configuration
     * savers that need to be injected into the generated saver as dependencies.
     *
     * <p>For a {@code List<OtherConfig>}, it will find and add a dependency for {@code
     * OtherConfigSaver}.
     *
     * @param type               the property type (or component/argument type) to inspect (e.g. {@code
     *                           List<OtherConfig>})
     * @param builder            the TypeSpec builder of the saver class
     * @param constructorBuilder the constructor builder of the saver class
     */
    private void collectSaverDependencies(
            TypeMirror type, TypeSpec.Builder builder, MethodSpec.Builder constructorBuilder) {
        if (typesUtil.isConfigType(type)) {
            addSaverDependency(builder, constructorBuilder, type);
            return;
        }

        TypeMirrorWrapper wrapped = TypeMirrorWrapper.wrap(type);
        if (wrapped.hasTypeArguments()) {
            for (TypeMirror arg : wrapped.getTypeArguments()) {
                collectSaverDependencies(arg, builder, constructorBuilder);
            }
        }
    }

    /**
     * Recursively traverses generic type arguments of a property's type to discover non-static custom
     * serializers that need to be injected into the generated saver.
     *
     * <p>Generates:
     *
     * <pre>{@code
     * private final Provider<MyCustomSerializer> myCustomSerializerProvider;
     *
     * @Inject
     * public MyConfigSaver(Provider<MyCustomSerializer> myCustomSerializerProvider) {
     *     this.myCustomSerializerProvider = myCustomSerializerProvider;
     * }
     * }</pre>
     *
     * @param type               the property type (or component/argument type) to inspect (e.g. {@code Map<String,
     *                           CustomType>})
     * @param injectedTypes      the set of already registered injected Types to add to
     * @param injectedFieldNames the mapping of injected types to their corresponding field names
     *                           (e.g. {@code myCustomSerializerProvider})
     */
    private void collectCustomSerializers(
            TypeMirror type, Set<TypeName> injectedTypes, Map<TypeName, String> injectedFieldNames) {
        customSerializers
                .getCustomInfo(type)
                .ifPresent(
                        info -> {
                            if (!info.isStatic()) {
                                TypeElement serializerClass = info.serializerClass();
                ClassName serializerClassName = ClassName.get(serializerClass);
                                String fieldName =
                                        Strings.uncapitalize(serializerClass.getSimpleName().toString())
                                                + ConfigurationClassNameGenerator.PROVIDER_SUFFIX;
                                if (injectedTypes.add(serializerClassName)) {
                                    injectedFieldNames.put(serializerClassName, fieldName);
                }
              }
            });

    TypeMirrorWrapper wrapped = TypeMirrorWrapper.wrap(type);
    if (wrapped.hasTypeArguments()) {
      for (TypeMirror arg : wrapped.getTypeArguments()) {
        collectCustomSerializers(arg, injectedTypes, injectedFieldNames);
      }
    }
  }
}
