package me.bristermitten.mittenlib.annotations.compile;

import com.squareup.javapoet.*;
import me.bristermitten.mittenlib.annotations.ast.AbstractConfigStructure;
import me.bristermitten.mittenlib.annotations.ast.ConfigTypeSource;
import me.bristermitten.mittenlib.annotations.ast.Property;
import me.bristermitten.mittenlib.annotations.ast.ValidationConstraint;
import me.bristermitten.mittenlib.annotations.config.ConfigProcessor;
import me.bristermitten.mittenlib.config.exception.ConfigValidationException;
import me.bristermitten.mittenlib.util.Result;

import javax.annotation.processing.Generated;
import javax.inject.Inject;
import javax.lang.model.element.Modifier;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class ConfigValidatorGenerator {
    private final ConfigurationClassNameGenerator classNameGenerator;
    private final FieldNameGenerator fieldNameGenerator;
    private final MethodNames methodNames;

    @Inject
    public ConfigValidatorGenerator(
            ConfigurationClassNameGenerator classNameGenerator,
            FieldNameGenerator fieldNameGenerator,
            MethodNames methodNames) {
        this.classNameGenerator = classNameGenerator;
        this.fieldNameGenerator = fieldNameGenerator;
        this.methodNames = methodNames;
    }

    public JavaFile emit(AbstractConfigStructure ast) {
        ClassName validatorClassName = classNameGenerator.getValidatorClassName(ast);
        TypeSpec.Builder builder = createValidatorBuilder(ast);
        addChildValidatorClasses(ast, builder);

        return JavaFile.builder(validatorClassName.packageName(), builder.build()).build();
    }

    private void addChildValidatorClasses(AbstractConfigStructure ast, TypeSpec.Builder builder) {
        for (AbstractConfigStructure child : ast.enclosed()) {
            TypeSpec.Builder childBuilder = createValidatorBuilder(child);
            addChildValidatorClasses(child, childBuilder);
            builder.addType(childBuilder.build());
        }
    }

    private TypeSpec.Builder createValidatorBuilder(AbstractConfigStructure ast) {
        ClassName validatorClassName = classNameGenerator.getValidatorClassName(ast);
        ClassName publicClassName = classNameGenerator.getPublicClassName(ast);

        TypeSpec.Builder builder = TypeSpec.classBuilder(validatorClassName.simpleName())
                .addModifiers(Modifier.PUBLIC);

        if (ast.enclosedIn() != null) {
            builder.addModifiers(Modifier.STATIC);
        }

        // Add @Generated annotation
        builder.addAnnotation(AnnotationSpec.builder(Generated.class)
                .addMember("value", "$S", ConfigProcessor.class.getName())
                .addMember("comments", "$S", "Generated by MittenLib Annotation Processor")
                .addMember("date", "$S", ZonedDateTime.now(ZoneId.systemDefault()).format(DateTimeFormatter.ISO_INSTANT))
                .build()
        );

        // Fields
        addValidatorFields(ast, builder);

        // Constructor 1: Guice @Inject constructor
        addGuiceConstructor(ast, builder);

        // Constructor 2: Overloaded/No-args constructor for programmatic usage
        addOverloadedConstructor(ast, builder);

        // validate() method
        addValidateMethod(ast, builder, publicClassName);

        return builder;
    }

    private void addValidatorFields(AbstractConfigStructure ast, TypeSpec.Builder builder) {
        for (Property property : ast.properties()) {
            for (ValidationConstraint constraint : property.settings().constraints()) {
                if (constraint instanceof ValidationConstraint.Custom(ClassName validatorClassName)) {
                    FieldSpec validatorField = FieldSpec.builder(
                            validatorClassName,
                            property.name() + "Validator",
                            Modifier.PRIVATE, Modifier.FINAL
                    ).build();
                    builder.addField(validatorField);
                }
            }
        }
    }

    private void addGuiceConstructor(AbstractConfigStructure ast, TypeSpec.Builder builder) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addAnnotation(Inject.class)
                .addModifiers(Modifier.PUBLIC);

        boolean hasCustom = false;
        for (Property property : ast.properties()) {
            for (ValidationConstraint constraint : property.settings().constraints()) {
                if (constraint instanceof ValidationConstraint.Custom(ClassName validatorClassName)) {
                    String fieldName = property.name() + "Validator";
                    constructor.addParameter(validatorClassName, fieldName);
                    constructor.addStatement("this.$L = $L", fieldName, fieldName);
                    hasCustom = true;
                }
            }
        }

        if (hasCustom) {
            builder.addMethod(constructor.build());
        }
    }

    private void addOverloadedConstructor(AbstractConfigStructure ast, TypeSpec.Builder builder) {
        List<Property> customValidatedProperties = ast.properties().stream()
                .filter(p -> p.settings().constraints().stream().anyMatch(c -> c instanceof ValidationConstraint.Custom))
                .toList();

        if (customValidatedProperties.isEmpty()) {
            // No custom validators, so the class has a default compiler-generated no-arg constructor
            return;
        }

        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC);

        for (Property property : customValidatedProperties) {
            for (ValidationConstraint constraint : property.settings().constraints()) {
                if (constraint instanceof ValidationConstraint.Custom(ClassName validatorClassName)) {
                    String fieldName = property.name() + "Validator";
                    constructor.addStatement("this.$L = new $T()", fieldName, validatorClassName);
                }
            }
        }

        builder.addMethod(constructor.build());
    }

    private void addValidateMethod(AbstractConfigStructure ast, TypeSpec.Builder builder, ClassName publicClassName) {
        MethodSpec.Builder validateMethod = MethodSpec.methodBuilder("validate")
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(ClassName.get(Result.class), publicClassName))
                .addParameter(publicClassName, "config", Modifier.FINAL);

        validateMethod.addStatement("$T<$T.Violation> violations = new $T<>()",
                List.class, ConfigValidationException.class, ArrayList.class);

        for (Property property : ast.properties()) {
            List<ValidationConstraint> constraints = property.settings().constraints();
            boolean isNullable = property.settings().isNullable();
            boolean isPrimitive = TypeName.get(property.propertyType()).isPrimitive();
            String accessorCall = "config." + methodNames.safeMethodName(property) + "()";
            String configKey = fieldNameGenerator.getConfigFieldName(property);

            if (constraints.isEmpty() && isNullable) {
                continue;
            }


            if (!isPrimitive) {
                if (!isNullable) {
                    // Property is NOT nullable: generate a null check
                    validateMethod.beginControlFlow("if ($L == null)", accessorCall);
                    validateMethod.addStatement("violations.add(new $T.Violation($S, null, $S))",
                            ConfigValidationException.class, configKey, "Must not be null");
                    if (!constraints.isEmpty()) {
                        validateMethod.nextControlFlow("else");
                    } else {
                        validateMethod.endControlFlow();
                    }
                } else {
                    // Property IS nullable: only validate other constraints if it's not null
                    validateMethod.beginControlFlow("if ($L != null)", accessorCall);
                }
            }

            if (!constraints.isEmpty()) {
                for (ValidationConstraint constraint : constraints) {
                    switch (constraint) {
                        case ValidationConstraint.Positive() -> {
                            validateMethod.beginControlFlow("if ($L <= 0)", accessorCall);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $S))",
                                    ConfigValidationException.class, configKey, accessorCall, "Must be positive");
                            validateMethod.endControlFlow();
                        }
                        case ValidationConstraint.Negative() -> {
                            validateMethod.beginControlFlow("if ($L >= 0)", accessorCall);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $S))",
                                    ConfigValidationException.class, configKey, accessorCall, "Must be negative");
                            validateMethod.endControlFlow();
                        }
                        case ValidationConstraint.Min(double val) -> {
                            validateMethod.beginControlFlow("if ($L < $L)", accessorCall, val);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $S + $L))",
                                    ConfigValidationException.class, configKey, accessorCall, "Must be at least ", val);
                            validateMethod.endControlFlow();
                        }
                        case ValidationConstraint.Max(double val) -> {
                            validateMethod.beginControlFlow("if ($L > $L)", accessorCall, val);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $S + $L))",
                                    ConfigValidationException.class, configKey, accessorCall, "Must be at most ", val);
                            validateMethod.endControlFlow();
                        }
                        case ValidationConstraint.Range(double min, double max) -> {
                            validateMethod.beginControlFlow("if ($L < $L || $L > $L)", accessorCall, min, accessorCall, max);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $S + $L + $S + $L))",
                                    ConfigValidationException.class, configKey, accessorCall, "Must be between ", min, " and ", max);
                            validateMethod.endControlFlow();
                        }
                        case ValidationConstraint.NotBlank() -> {
                            validateMethod.beginControlFlow("if ($L.trim().isEmpty())", accessorCall);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $S))",
                                    ConfigValidationException.class, configKey, accessorCall, "Must not be blank");
                            validateMethod.endControlFlow();
                        }
                        case ValidationConstraint.Custom(ClassName validatorClassName) -> {
                            String validatorFieldName = "this." + property.name() + "Validator";
                            String errorFieldName = property.name() + "ValidationError";
                            validateMethod.addStatement("$T<$T> $L = $L.validate($L)",
                                    java.util.Optional.class, String.class, errorFieldName, validatorFieldName, accessorCall);
                            validateMethod.beginControlFlow("if ($L.isPresent())", errorFieldName);
                            validateMethod.addStatement("violations.add(new $T.Violation($S, $L, $L.get()))",
                                    ConfigValidationException.class, configKey, accessorCall, errorFieldName);
                            validateMethod.endControlFlow();
                        }
                    }
                }
            }

            if (!isPrimitive && (isNullable || !constraints.isEmpty())) {
                // Close the outer if/else block
                validateMethod.endControlFlow();
            }
        }

        validateMethod.beginControlFlow("if (!violations.isEmpty())");
        validateMethod.addStatement("return $T.fail(new $T(config.getClass(), violations))",
                Result.class, ConfigValidationException.class);
        validateMethod.endControlFlow();

        validateMethod.addStatement("return $T.ok(config)", Result.class);
        builder.addMethod(validateMethod.build());
    }
}
