package me.bristermitten.mittenlib.annotations.compile;

import com.squareup.javapoet.*;
import io.toolisticon.aptk.tools.TypeMirrorWrapper;
import me.bristermitten.mittenlib.annotations.ast.AbstractConfigStructure;
import me.bristermitten.mittenlib.annotations.ast.ConfigTypeSource;
import me.bristermitten.mittenlib.annotations.ast.CustomDeserializerInfo;
import me.bristermitten.mittenlib.annotations.ast.Property;
import me.bristermitten.mittenlib.annotations.config.ConfigProcessor;
import me.bristermitten.mittenlib.annotations.parser.CustomDeserializers;
import me.bristermitten.mittenlib.annotations.util.TypesUtil;
import me.bristermitten.mittenlib.config.DeserializationContext;
import me.bristermitten.mittenlib.config.DeserializationFunction;
import me.bristermitten.mittenlib.config.exception.ConfigLoadingErrors;
import me.bristermitten.mittenlib.util.Result;
import me.bristermitten.mittenlib.util.Strings;
import org.jspecify.annotations.Nullable;

import javax.annotation.processing.Generated;
import javax.inject.Inject;
import javax.inject.Provider;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class ConfigLoaderGenerator {

    private final ConfigurationClassNameGenerator classNameGenerator;
    private final DeserializationCodeGenerator deserializationCodeGenerator;
    private final CustomDeserializers customDeserializers;
    private final TypesUtil typesUtil;

    @Inject
    public ConfigLoaderGenerator(
            ConfigurationClassNameGenerator classNameGenerator,
            DeserializationCodeGenerator deserializationCodeGenerator,
            CustomDeserializers customDeserializers,
            TypesUtil typesUtil) {
        this.classNameGenerator = classNameGenerator;
        this.deserializationCodeGenerator = deserializationCodeGenerator;
        this.customDeserializers = customDeserializers;
        this.typesUtil = typesUtil;
    }

    /**
     * Entry point for generating a {@link JavaFile} for a configuration loader.
     *
     * @param ast the configuration structure to generate a loader for
     * @return a {@link JavaFile} containing the generated loader class
     */
    public JavaFile emit(AbstractConfigStructure ast) {
        ClassName loaderClassName = classNameGenerator.getLoaderClassName(ast);
        TypeSpec.Builder builder = createLoaderBuilder(ast);
        addChildLoaderClasses(ast, builder);

        return JavaFile.builder(loaderClassName.packageName(), builder.build()).build();
    }

    /**
     * Creates the {@link TypeSpec.Builder} for the loader class, including its annotations,
     * fields, constructor, and deserialization methods.
     *
     * @param ast the configuration structure
     * @return a builder for the loader class
     */
    private TypeSpec.Builder createLoaderBuilder(AbstractConfigStructure ast) {
        ClassName loaderClassName = classNameGenerator.getLoaderClassName(ast);
        ClassName publicClassName = classNameGenerator.getPublicClassName(ast);

        TypeSpec.Builder builder = TypeSpec.classBuilder(loaderClassName.simpleName())
                .addModifiers(Modifier.PUBLIC)
                .addSuperinterface(ParameterizedTypeName.get(ClassName.get(DeserializationFunction.class), publicClassName));

        if (ast.enclosedIn() != null) {
            builder.addModifiers(Modifier.STATIC);
        }

        // Add @Generated annotation
        builder.addAnnotation(AnnotationSpec.builder(Generated.class)
                .addMember("value", "$S", ConfigProcessor.class.getName())
                .addMember("comments", "$S", "Generated by MittenLib Annotation Processor")
                .addMember("date", "$S", ZonedDateTime.now(ZoneId.systemDefault()).format(DateTimeFormatter.ISO_INSTANT))
                .build()
        );

        // Collect fields & constructor dependencies
        addFieldsAndConstructor(ast, builder);

        // Add property deserialization methods
        ClassName daoName = GeneratorUtil.getDaoName(ast, classNameGenerator);

        var dtoType = ast.source().element();
        final List<MethodSpec> deserializeMethods = ast.properties().stream()
                .map(property -> deserializationCodeGenerator.createDeserializeMethodFor(dtoType, ast, property, daoName))
                .toList();

        deserializeMethods.forEach(builder::addMethod);

        // Add apply() method
        addApplyMethod(ast, builder, deserializeMethods, daoName);

        return builder;
    }

    /**
     * Recursively adds nested loader classes for enclosed configuration structures.
     *
     * @param ast           the parent configuration structure
     * @param loaderBuilder the builder for the parent loader class
     */
    private void addChildLoaderClasses(AbstractConfigStructure ast, TypeSpec.Builder loaderBuilder) {
        for (AbstractConfigStructure child : ast.enclosed()) {
            TypeSpec.Builder childLoaderBuilder = createLoaderBuilder(child);
            addChildLoaderClasses(child, childLoaderBuilder);
            loaderBuilder.addType(childLoaderBuilder.build());
        }
    }

    /**
     * Adds fields and a {@code @Inject} constructor to the loader class for its dependencies,
     * such as sub-loaders, custom deserializers, and validators.
     * <p>
     * Generates:
     * <pre>{@code
     *     private final Provider<OtherConfigLoader> otherConfigLoader;
     *     private final MyDeserializer myDeserializer;
     *
     *     @Inject
     *     public MyConfigLoader(Provider<OtherConfigLoader> otherConfigLoader, MyDeserializer myDeserializer) {
     *         this.otherConfigLoader = otherConfigLoader;
     *         this.myDeserializer = myDeserializer;
     *     }
     * }</pre>
     *
     * @param ast     the configuration structure, used to determine dependencies like {@code otherConfigLoader} or {@code myDeserializer}
     * @param builder the loader class builder
     */
    private void addFieldsAndConstructor(AbstractConfigStructure ast, TypeSpec.Builder builder) {
        MethodSpec.Builder constructor = MethodSpec.constructorBuilder()
                .addAnnotation(Inject.class)
                .addModifiers(Modifier.PUBLIC);

        // Injected Validator if validation is needed
        if (ast.needsValidation()) {
            ClassName validatorClassName = classNameGenerator.getValidatorClassName(ast);
            String validatorFieldName = "validator";
            builder.addField(FieldSpec.builder(validatorClassName, validatorFieldName, Modifier.PRIVATE, Modifier.FINAL).build());
            constructor.addParameter(validatorClassName, validatorFieldName);
            constructor.addStatement("this.$L = $L", validatorFieldName, validatorFieldName);
        }

        // Referenced Sub-loaders & Non-static Custom Deserializers
        Set<TypeName> injectedTypes = new LinkedHashSet<>();
        Map<TypeName, String> injectedFieldNames = new LinkedHashMap<>();

        for (TypeMirror parent : ast.source().parents()) {
            collectConfigTypes(parent, injectedTypes, injectedFieldNames);
        }

        if (ast instanceof AbstractConfigStructure.Union union) {
            for (AbstractConfigStructure alternative : union.alternatives()) {
                collectConfigTypes(alternative.source().element().asType(), injectedTypes, injectedFieldNames);
            }
        }

        for (Property property : ast.properties()) {
            // Check for custom deserializers recursively
            collectCustomDeserializers(property.propertyType(), injectedTypes, injectedFieldNames);

            // Check config types
            TypeMirror type = property.propertyType();
            collectConfigTypes(type, injectedTypes, injectedFieldNames);
        }

        for (TypeName typeName : injectedTypes) {
            String fieldName = injectedFieldNames.get(typeName);
            builder.addField(FieldSpec.builder(typeName, fieldName, Modifier.PRIVATE, Modifier.FINAL).build());
            constructor.addParameter(typeName, fieldName);
            constructor.addStatement("this.$L = $L", fieldName, fieldName);
        }

        builder.addMethod(constructor.build());
    }

    /**
     * Collects configuration types that need to be injected as sub-loaders.
     *
     * @param type               the type to inspect
     * @param injectedTypes      the set of already registered injected Types to add to
     * @param injectedFieldNames the mapping of injected types to their corresponding field names
     */
    private void collectConfigTypes(TypeMirror type, Set<TypeName> injectedTypes, Map<TypeName, String> injectedFieldNames) {
        if (typesUtil.isConfigType(type)) {
            ClassName subLoaderName = classNameGenerator.getLoaderClassName(type);
            TypeName providerType = ParameterizedTypeName.get(ClassName.get(Provider.class), subLoaderName);
            String fieldName = classNameGenerator.getLoaderProviderFieldName(type);
            if (injectedTypes.add(providerType)) {
                injectedFieldNames.put(providerType, fieldName);
            }
            return;
        }

        TypeMirrorWrapper wrapped = TypeMirrorWrapper.wrap(type);
        if (wrapped.hasTypeArguments()) {
            for (TypeMirror arg : wrapped.getTypeArguments()) {
                collectConfigTypes(arg, injectedTypes, injectedFieldNames);
            }
        }
    }

    /**
     * Recursively traverses generic type arguments of a property's type to discover
     * non-static custom deserializers that need to be injected into the generated loader.
     *
     * @param type               the property type (or component/argument type) to inspect
     * @param injectedTypes      the set of already registered injected Types to add to
     * @param injectedFieldNames the mapping of injected types to their corresponding field names
     */
    private void collectCustomDeserializers(TypeMirror type, Set<TypeName> injectedTypes, Map<TypeName, String> injectedFieldNames) {
        Optional<CustomDeserializerInfo> deserializerOpt = customDeserializers.getCustomDeserializer(type);
        if (deserializerOpt.isPresent()) {
            CustomDeserializerInfo info = deserializerOpt.get();
            if (!info.isStatic()) {
                TypeElement deserializerClass = info.deserializerClass();
                String fieldName = Strings.uncapitalize(deserializerClass.getSimpleName().toString());
                ClassName deserializerClassName = ClassName.get(deserializerClass);
                if (injectedTypes.add(deserializerClassName)) {
                    injectedFieldNames.put(deserializerClassName, fieldName);
                }
            }
        }

        TypeMirrorWrapper wrapped = TypeMirrorWrapper.wrap(type);
        if (wrapped.hasTypeArguments()) {
            for (TypeMirror arg : wrapped.getTypeArguments()) {
                collectCustomDeserializers(arg, injectedTypes, injectedFieldNames);
            }
        }
    }

    /**
     * Adds the {@code apply} method to the loader, which orchestrates the deserialization of all properties.
     * <p>
     * Generates a recursive {@code flatMap} chain:
     * <pre>{@code
     *     public Result<MyConfig> apply(DeserializationContext context) {
     *         MyConfigDAO dao = new MyConfigDAO();
     *         return deserializeCount(context, dao).flatMap(var0 ->
     *             deserializeName(context, dao).flatMap(var1 ->
     *                 Result.ok((MyConfig) new MyConfigImpl(var0, var1))
     *             )
     *         );
     *     }
     * }</pre>
     *
     * @param ast                the configuration structure, used to determine the return type (e.g. {@code MyConfig})
     * @param builder            the loader class builder
     * @param deserializeMethods the list of generated property deserialization methods (e.g. {@code deserializeCount}, {@code deserializeName})
     * @param daoName            the name of the DAO class, if applicable (e.g. {@code MyConfigDAO})
     */
    private void addApplyMethod(AbstractConfigStructure ast, TypeSpec.Builder builder, List<MethodSpec> deserializeMethods, @Nullable ClassName daoName) {
        ClassName publicClassName = classNameGenerator.getPublicClassName(ast);
        ClassName implClassName = classNameGenerator.translateConfigClassName(ast);

        MethodSpec.Builder applyMethod = MethodSpec.methodBuilder("apply")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .returns(ParameterizedTypeName.get(ClassName.get(Result.class), publicClassName))
                .addParameter(DeserializationContext.class, "context", Modifier.FINAL);

        if (ast instanceof AbstractConfigStructure.Union union) {
            CodeBlock.Builder deserialiseBuilder = CodeBlock.builder();
            deserialiseBuilder.add("return ");
            for (AbstractConfigStructure alternative : union.alternatives()) {
                String loaderFieldName = classNameGenerator.getLoaderProviderFieldName(alternative.source().element().asType());

                deserialiseBuilder.add("this.$L.get().apply(context).map($T.class::cast).orElse(() -> \n",
                        loaderFieldName,
                        publicClassName);
                deserialiseBuilder.indent();
            }
            deserialiseBuilder.add("$T.fail($T.noUnionMatch())", Result.class, ConfigLoadingErrors.class);
            deserialiseBuilder.add(")".repeat(union.alternatives().size()));

            applyMethod.addStatement(deserialiseBuilder.build());
            builder.addMethod(applyMethod.build());
            return;
        }

        GeneratorUtil.addDaoInstantiationIfNecessary(ast, applyMethod, daoName);

        final CodeBlock.Builder expressionBuilder = CodeBlock.builder();
        expressionBuilder.add("return ");
        int i = 0;

        var superClass = switch (ast.source()) {
            case ConfigTypeSource.ClassConfigTypeSource c -> c.parent();
            case ConfigTypeSource.InterfaceConfigTypeSource ignored -> Optional.<TypeMirror>empty();
        };

        if (superClass.isPresent()) {
            String superLoaderFieldName = classNameGenerator.getLoaderProviderFieldName(superClass.get());
            expressionBuilder.add("this.$L.get().apply(context).flatMap(var$L -> \n", superLoaderFieldName, i++);
        }

        for (int idx = 0; idx < deserializeMethods.size(); idx++) {
            MethodSpec deserializeMethod = deserializeMethods.get(idx);
            Property property = ast.properties().get(idx);
            var deserializeMethodArguments = (daoName != null && property.settings().hasDefaultValue()) ? "context, dao" : "context";
            expressionBuilder.add("$N($L).flatMap(var$L -> \n", deserializeMethod, deserializeMethodArguments, i++);
        }

        expressionBuilder.add("$T.ok(($T) new $T(", Result.class, publicClassName, implClassName);
        for (int i1 = 0; i1 < i; i1++) {
            expressionBuilder.add("var$L", i1);
            if (i1 != i - 1) {
                expressionBuilder.add(", ");
            }
        }

        expressionBuilder.add("))"); // Close ok and new parens

        if (ast.needsValidation()) {
            expressionBuilder.add(".flatMap(this.validator::validate)");
        }
        expressionBuilder.add(")".repeat(Math.max(0, i))); // close all flatMap parens

        applyMethod.addStatement(expressionBuilder.build());
        builder.addMethod(applyMethod.build());
    }


}
