package me.bristermitten.mittenlib.annotations.compile;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import java.util.Objects;
import javax.annotation.processing.Generated;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;
import me.bristermitten.mittenlib.annotations.config.ConfigProcessor;
import me.bristermitten.mittenlib.annotations.util.NewtypeUtil;

public class NewtypeImplGenerator {

    public JavaFile emit(TypeElement element) {
        ClassName publicClassName = ClassName.get(element);
        ClassName implClassName = NewtypeUtil.getImplClassName(element);

        TypeSpec.Builder builder = TypeSpec.classBuilder(implClassName)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addSuperinterface(publicClassName)
                .addAnnotation(AnnotationSpec.builder(Generated.class)
                        .addMember("value", "$S", ConfigProcessor.class.getName())
                        .addMember("comments", "$S", "Generated by MittenLib Annotation Processor")
                        .build());

        ExecutableElement method = ElementFilter.methodsIn(element.getEnclosedElements()).stream()
                .filter(m -> !m.isDefault() && !m.getModifiers().contains(Modifier.STATIC))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("No abstract method found in newtype interface"));

        String fieldName = method.getSimpleName().toString();
        TypeName typeName = TypeName.get(method.getReturnType());

        // Field
        builder.addField(FieldSpec.builder(typeName, fieldName, Modifier.PRIVATE, Modifier.FINAL)
                .build());

        // Constructor
        builder.addMethod(MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addParameter(typeName, fieldName)
                .addStatement("this.$1L = $1L", fieldName)
                .build());

        // Getter
        builder.addMethod(MethodSpec.methodBuilder(fieldName)
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(typeName)
                .addStatement("return this.$L", fieldName)
                .build());

        // equals
        builder.addMethod(MethodSpec.methodBuilder("equals")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(boolean.class)
                .addParameter(Object.class, "o")
                .addStatement("if (this == o) return true")
                .addStatement("if (!(o instanceof $T)) return false", publicClassName)
                .addStatement("$T other = ($T) o", publicClassName, publicClassName)
                .addStatement("return $T.equals(this.$L, other.$L())", Objects.class, fieldName, fieldName)
                .build());

        // hashCode
        builder.addMethod(MethodSpec.methodBuilder("hashCode")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(int.class)
                .addStatement("return $T.hash(this.$L)", Objects.class, fieldName)
                .build());

        // toString
        builder.addMethod(MethodSpec.methodBuilder("toString")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(String.class)
                .addStatement("return $S + $L + $S", implClassName.simpleName() + "{" + fieldName + "=", fieldName, "}")
                .build());

        return JavaFile.builder(implClassName.packageName(), builder.build())
                .skipJavaLangImports(true)
                .build();
    }
}
