package me.bristermitten.mittenlib.codegen.union

import com.palantir.javapoet.*
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.util.Optional
import javax.annotation.processing.Generated
import javax.lang.model.element.Modifier
import me.bristermitten.mittenlib.codegen.BoilerplateGenerator
import me.bristermitten.mittenlib.codegen.GeneratedUnion
import me.bristermitten.mittenlib.codegen.record.RecordConstructorSpec
import me.bristermitten.mittenlib.codegen.record.RecordGenerator
import scala.jdk.CollectionConverters.*

object UnionGenerator:

  private def addSealingConstructor(typeSpecBuilder: TypeSpec.Builder): Unit =
    typeSpecBuilder.addMethod(
      MethodSpec.constructorBuilder()
        .addModifiers(Modifier.PRIVATE)
        .addCode(
          typeSpecBuilder.build().typeSpecs.asScala
            .map(m => CodeBlock.of("this instanceof $L", m.name()))
            .asJava.stream().collect(CodeBlock.joining(" || ", "if (!(", """
              )) {
                  throw new UnsupportedOperationException("Union type is sealed!: " + this.getClass().getName());
              }
              """))
        )
        .build()
    )

  private def generateAsMethod(
    constructorClassName: ClassName,
    constructor: RecordConstructorSpec,
    typeSpecBuilder: TypeSpec.Builder
  ): Unit =
    typeSpecBuilder.addMethod(
      MethodSpec.methodBuilder(s"as${constructor.name}")
        .addModifiers(Modifier.PUBLIC)
        .returns(ParameterizedTypeName.get(ClassName.get(classOf[Optional[?]]), constructorClassName))
        .addCode(
          CodeBlock.builder()
            .beginControlFlow("if (this instanceof $L)", constructorClassName)
            .addStatement("return $T.of(($T) this)", classOf[Optional[?]], constructorClassName)
            .endControlFlow()
            .addStatement("return $T.empty()", classOf[Optional[?]])
            .build()
        )
        .build()
    )

  private def resolve(unionSpec: UnionSpec): ResolvedUnionSpec =
    new ResolvedUnionSpec(
      unionSpec.source,
      unionSpec.name,
      unionSpec.strategy,
      unionSpec.constructors.asScala.map { constructor =>
        new ResolvedUnionConstructor(
          unionSpec.source,
          unionSpec.name.nestedClass(constructor.name),
          constructor
        )
      }.asJava
    )

class UnionGenerator:
  import UnionGenerator.*

  def generate(unionSpec: UnionSpec): JavaFile =
    val recordImplName = unionSpec.name
    val typeSpecBuilder = TypeSpec.classBuilder(recordImplName)
    typeSpecBuilder.addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)

    typeSpecBuilder.addAnnotation(
      AnnotationSpec.builder(classOf[GeneratedUnion])
        .addMember("source", "$T.class", unionSpec.source)
        .build()
    )

    typeSpecBuilder.addAnnotation(
      AnnotationSpec.builder(classOf[Generated])
        .addMember("value", "$S", "me.bristermitten.mittenlib.codegen.BoilerplateGenerator")
        .addMember("comments", "$S", "Generated by MittenLib Annotation Processor")
        .addMember(
          "date", "$S", ZonedDateTime.now(ZoneId.systemDefault()).format(DateTimeFormatter.ISO_INSTANT)
        )
        .build()
    )

    val resolved = resolve(unionSpec)

    typeSpecBuilder.addMethod(MatchGenerator.makeVoidMatchMethodSpec(resolved, true))
    typeSpecBuilder.addMethod(MatchGenerator.makeMatchMethodSpec(resolved, true))

    for (toGenerate <- resolved.constructors.asScala) {
      val generatedRecord = RecordGenerator.generateBasicRecordTypeSpec(toGenerate, false)
      val constructorTypeSpecBuilder = generatedRecord.typeSpecBuilder.addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)

      constructorTypeSpecBuilder.superclass(recordImplName)

      RecordGenerator.addFactoryMethod(toGenerate.constructor, toGenerate.name, typeSpecBuilder)
      generateAsMethod(toGenerate.name, toGenerate.constructor, typeSpecBuilder)

      constructorTypeSpecBuilder.addMethod(MatchGenerator.implementVoidMatchMethod(resolved, toGenerate))
      constructorTypeSpecBuilder.addMethod(MatchGenerator.implementReturningMatchMethod(resolved, toGenerate))

      typeSpecBuilder.addType(constructorTypeSpecBuilder.build())
    }

    addSealingConstructor(typeSpecBuilder)

    JavaFile.builder(recordImplName.packageName(), typeSpecBuilder.build()).build()
