package me.bristermitten.mittenlib.annotations.integration;

import com.google.inject.Inject;
import java.lang.Override;
import java.lang.String;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.annotation.processing.Generated;
import me.bristermitten.mittenlib.config.SerializationContext;
import me.bristermitten.mittenlib.config.SerializationFunction;
import me.bristermitten.mittenlib.config.tree.DataTree;
import me.bristermitten.mittenlib.config.tree.DataTreeTransforms;

@Generated(
    value = "me.bristermitten.mittenlib.annotations.config.ConfigProcessor",
    comments = "Generated by MittenLib Annotation Processor",
    date = "2026-06-08T11:51:03.906465Z"
)
public class ValidationConfigImplSerializer implements SerializationFunction<ValidationConfigImpl> {
  @Inject
  public ValidationConfigImplSerializer() {
  }

  @Override
  public DataTree apply(ValidationConfigImpl config, SerializationContext context) {
    Map<DataTree, DataTree> map = new LinkedHashMap<>();
    map.put(DataTree.string("positiveInt"), this.serializePositiveInt(config.positiveInt(), context));
    map.put(DataTree.string("negativeDouble"), this.serializeNegativeDouble(config.negativeDouble(), context));
    map.put(DataTree.string("minInt"), this.serializeMinInt(config.minInt(), context));
    map.put(DataTree.string("maxLong"), this.serializeMaxLong(config.maxLong(), context));
    map.put(DataTree.string("rangeDouble"), this.serializeRangeDouble(config.rangeDouble(), context));
    map.put(DataTree.string("notBlankString"), this.serializeNotBlankString(config.notBlankString(), context));
    map.put(DataTree.string("customValidated"), this.serializeCustomValidated(config.customValidated(), context));
    return DataTree.map(map);
  }

  @Override
  public DataTree generateDefault(SerializationContext context) {
    Map<DataTree, DataTree> map = new LinkedHashMap<>();
    map.put(DataTree.string("positiveInt"), DataTree.null_());
    map.put(DataTree.string("negativeDouble"), DataTree.null_());
    map.put(DataTree.string("minInt"), DataTree.null_());
    map.put(DataTree.string("maxLong"), DataTree.null_());
    map.put(DataTree.string("rangeDouble"), DataTree.null_());
    map.put(DataTree.string("notBlankString"), DataTree.null_());
    map.put(DataTree.string("customValidated"), DataTree.null_());
    return DataTree.map(map);
  }

  private DataTree serializePositiveInt(int value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }

  private DataTree serializeNegativeDouble(double value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }

  private DataTree serializeMinInt(int value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }

  private DataTree serializeMaxLong(long value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }

  private DataTree serializeRangeDouble(double value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }

  private DataTree serializeNotBlankString(String value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }

  private DataTree serializeCustomValidated(String value, SerializationContext context) {
    DataTree result;
    result = DataTreeTransforms.loadFrom(value);
    return result;
  }
}
