package me.bristermitten.mittenlib.annotations.integration;

import com.google.inject.Inject;
import java.lang.String;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.annotation.processing.Generated;
import me.bristermitten.mittenlib.config.exception.ConfigValidationException;
import me.bristermitten.mittenlib.util.Result;

@Generated(
    value = "me.bristermitten.mittenlib.annotations.config.ConfigProcessor",
    comments = "Generated by MittenLib Annotation Processor",
    date = "2026-06-08T11:51:03.906757Z"
)
public class ValidationConfigImplValidator {
  private final CustomStringValidator customValidatedValidator;

  @Inject
  public ValidationConfigImplValidator(CustomStringValidator customValidatedValidator) {
    this.customValidatedValidator = customValidatedValidator;
  }

  public Result<ValidationConfigImpl> validate(final ValidationConfigImpl config) {
    List<ConfigValidationException.Violation> violations = new ArrayList<>();
    if (config.positiveInt() <= 0) {
      violations.add(new ConfigValidationException.Violation("positiveInt", config.positiveInt(), "Must be positive"));
    }
    if (config.negativeDouble() >= 0) {
      violations.add(new ConfigValidationException.Violation("negativeDouble", config.negativeDouble(), "Must be negative"));
    }
    if (config.minInt() < 10.0) {
      violations.add(new ConfigValidationException.Violation("minInt", config.minInt(), "Must be at least " + 10.0));
    }
    if (config.maxLong() > 100.0) {
      violations.add(new ConfigValidationException.Violation("maxLong", config.maxLong(), "Must be at most " + 100.0));
    }
    if (config.rangeDouble() < 1.0 || config.rangeDouble() > 5.0) {
      violations.add(new ConfigValidationException.Violation("rangeDouble", config.rangeDouble(), "Must be between " + 1.0 + " and " + 5.0));
    }
    if (config.notBlankString() == null) {
      violations.add(new ConfigValidationException.Violation("notBlankString", null, "Must not be null"));
    } else {
      if (config.notBlankString().trim().isEmpty()) {
        violations.add(new ConfigValidationException.Violation("notBlankString", config.notBlankString(), "Must not be blank"));
      }
    }
    if (config.customValidated() == null) {
      violations.add(new ConfigValidationException.Violation("customValidated", null, "Must not be null"));
    } else {
      Optional<String> customValidatedValidationError = this.customValidatedValidator.validate(config.customValidated());
      if (customValidatedValidationError.isPresent()) {
        violations.add(new ConfigValidationException.Violation("customValidated", config.customValidated(), customValidatedValidationError.get()));
      }
    }
    if (!violations.isEmpty()) {
      return Result.fail(new ConfigValidationException(config.getClass(), violations));
    }
    return Result.ok(config);
  }
}
