package me.bristermitten.mittenlib.annotations.integration;

import com.google.gson.reflect.TypeToken;
import com.google.inject.Inject;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import javax.annotation.processing.Generated;
import me.bristermitten.mittenlib.config.DeserializationContext;
import me.bristermitten.mittenlib.config.DeserializationFunction;
import me.bristermitten.mittenlib.config.exception.ConfigLoadingErrors;
import me.bristermitten.mittenlib.config.tree.DataTree;
import me.bristermitten.mittenlib.util.Result;

@Generated(
    value = "me.bristermitten.mittenlib.annotations.config.ConfigProcessor",
    comments = "Generated by MittenLib Annotation Processor",
    date = "2026-06-08T11:51:03.905397Z"
)
public class ValidationConfigImplDeserializer implements DeserializationFunction<ValidationConfigImpl> {
  private final ValidationConfigImplValidator validator;

  @Inject
  public ValidationConfigImplDeserializer(ValidationConfigImplValidator validator) {
    this.validator = validator;
  }

  private Result<Integer> deserializePositiveInt(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree positiveIntFromMap = $data.get("positiveInt");
    if (positiveIntFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("positiveInt", "int", ValidationConfig.class, "positiveInt"));
    }
    if (positiveIntFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralInt) {
      return Result.ok((((DataTree.DataTreeLiteral.DataTreeLiteralInt) positiveIntFromMap).value()).intValue());
    }
    return context.getMapper().map(positiveIntFromMap, new TypeToken<Integer>(){});
  }

  private Result<Double> deserializeNegativeDouble(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree negativeDoubleFromMap = $data.get("negativeDouble");
    if (negativeDoubleFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("negativeDouble", "double", ValidationConfig.class, "negativeDouble"));
    }
    if (negativeDoubleFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralFloat) {
      return Result.ok((((DataTree.DataTreeLiteral.DataTreeLiteralFloat) negativeDoubleFromMap).value()).doubleValue());
    }
    return context.getMapper().map(negativeDoubleFromMap, new TypeToken<Double>(){});
  }

  private Result<Integer> deserializeMinInt(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree minIntFromMap = $data.get("minInt");
    if (minIntFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("minInt", "int", ValidationConfig.class, "minInt"));
    }
    if (minIntFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralInt) {
      return Result.ok((((DataTree.DataTreeLiteral.DataTreeLiteralInt) minIntFromMap).value()).intValue());
    }
    return context.getMapper().map(minIntFromMap, new TypeToken<Integer>(){});
  }

  private Result<Long> deserializeMaxLong(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree maxLongFromMap = $data.get("maxLong");
    if (maxLongFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("maxLong", "long", ValidationConfig.class, "maxLong"));
    }
    if (maxLongFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralInt) {
      return Result.ok((((DataTree.DataTreeLiteral.DataTreeLiteralInt) maxLongFromMap).value()).longValue());
    }
    return context.getMapper().map(maxLongFromMap, new TypeToken<Long>(){});
  }

  private Result<Double> deserializeRangeDouble(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree rangeDoubleFromMap = $data.get("rangeDouble");
    if (rangeDoubleFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("rangeDouble", "double", ValidationConfig.class, "rangeDouble"));
    }
    if (rangeDoubleFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralFloat) {
      return Result.ok((((DataTree.DataTreeLiteral.DataTreeLiteralFloat) rangeDoubleFromMap).value()).doubleValue());
    }
    return context.getMapper().map(rangeDoubleFromMap, new TypeToken<Double>(){});
  }

  private Result<String> deserializeNotBlankString(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree notBlankStringFromMap = $data.get("notBlankString");
    if (notBlankStringFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("notBlankString", "java.lang.String", ValidationConfig.class, "notBlankString"));
    }
    if (notBlankStringFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralString) {
      return Result.ok(((DataTree.DataTreeLiteral.DataTreeLiteralString) notBlankStringFromMap).value());
    }
    return context.getMapper().map(notBlankStringFromMap, new TypeToken<String>(){});
  }

  private Result<String> deserializeCustomValidated(DeserializationContext context) {
    DataTree $data = context.getData();
    DataTree customValidatedFromMap = $data.get("customValidated");
    if (customValidatedFromMap == null) {
      return Result.fail(ConfigLoadingErrors.notFoundException("customValidated", "java.lang.String", ValidationConfig.class, "customValidated"));
    }
    if (customValidatedFromMap instanceof DataTree.DataTreeLiteral.DataTreeLiteralString) {
      return Result.ok(((DataTree.DataTreeLiteral.DataTreeLiteralString) customValidatedFromMap).value());
    }
    return context.getMapper().map(customValidatedFromMap, new TypeToken<String>(){});
  }

  @Override
  public Result<ValidationConfigImpl> apply(final DeserializationContext context) {
    return deserializePositiveInt(context).flatMap(var0 -> 
        deserializeNegativeDouble(context).flatMap(var1 -> 
        deserializeMinInt(context).flatMap(var2 -> 
        deserializeMaxLong(context).flatMap(var3 -> 
        deserializeRangeDouble(context).flatMap(var4 -> 
        deserializeNotBlankString(context).flatMap(var5 -> 
        deserializeCustomValidated(context).flatMap(var6 -> 
        Result.ok((ValidationConfigImpl) new ValidationConfigImpl(var0, var1, var2, var3, var4, var5, var6)).flatMap(this.validator::validate))))))));
  }
}
