package me.bristermitten.mittenlib.annotations.integration;

import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import javax.annotation.processing.Generated;
import me.bristermitten.mittenlib.config.GeneratedConfig;
import org.jetbrains.annotations.Contract;
import org.jspecify.annotations.NonNull;

@GeneratedConfig(
    source = ValidationConfig.class,
    isDynamicallyInitializable = false,
    unserializableProperties = {
        "positiveInt",
        "negativeDouble",
        "minInt",
        "maxLong",
        "rangeDouble",
        "notBlankString",
        "customValidated"
    }
)
@Generated(
    value = "me.bristermitten.mittenlib.annotations.config.ConfigProcessor",
    comments = "Generated by MittenLib Annotation Processor",
    date = "2026-06-08T11:51:03.903963Z"
)
public class ValidationConfigImpl {
  private final @NonNull int positiveInt;

  private final @NonNull double negativeDouble;

  private final @NonNull int minInt;

  private final @NonNull long maxLong;

  private final @NonNull double rangeDouble;

  private final @NonNull String notBlankString;

  private final @NonNull String customValidated;

  public ValidationConfigImpl(final @NonNull int positiveInt, final @NonNull double negativeDouble,
      final @NonNull int minInt, final @NonNull long maxLong, final @NonNull double rangeDouble,
      final @NonNull String notBlankString, final @NonNull String customValidated) {
    this.positiveInt = positiveInt;
    this.negativeDouble = negativeDouble;
    this.minInt = minInt;
    this.maxLong = maxLong;
    this.rangeDouble = rangeDouble;
    this.notBlankString = notBlankString;
    this.customValidated = customValidated;
  }

  @Contract(
      pure = true
  )
  public @NonNull int positiveInt() {
    return positiveInt;
  }

  @Contract(
      pure = true
  )
  public @NonNull double negativeDouble() {
    return negativeDouble;
  }

  @Contract(
      pure = true
  )
  public @NonNull int minInt() {
    return minInt;
  }

  @Contract(
      pure = true
  )
  public @NonNull long maxLong() {
    return maxLong;
  }

  @Contract(
      pure = true
  )
  public @NonNull double rangeDouble() {
    return rangeDouble;
  }

  @Contract(
      pure = true
  )
  public @NonNull String notBlankString() {
    return notBlankString;
  }

  @Contract(
      pure = true
  )
  public @NonNull String customValidated() {
    return customValidated;
  }

  public ValidationConfigImpl withPositiveInt(final int positiveInt) {
    return new ValidationConfigImpl(positiveInt, this.negativeDouble, this.minInt, this.maxLong, this.rangeDouble, this.notBlankString, this.customValidated);
  }

  public ValidationConfigImpl withNegativeDouble(final double negativeDouble) {
    return new ValidationConfigImpl(this.positiveInt, negativeDouble, this.minInt, this.maxLong, this.rangeDouble, this.notBlankString, this.customValidated);
  }

  public ValidationConfigImpl withMinInt(final int minInt) {
    return new ValidationConfigImpl(this.positiveInt, this.negativeDouble, minInt, this.maxLong, this.rangeDouble, this.notBlankString, this.customValidated);
  }

  public ValidationConfigImpl withMaxLong(final long maxLong) {
    return new ValidationConfigImpl(this.positiveInt, this.negativeDouble, this.minInt, maxLong, this.rangeDouble, this.notBlankString, this.customValidated);
  }

  public ValidationConfigImpl withRangeDouble(final double rangeDouble) {
    return new ValidationConfigImpl(this.positiveInt, this.negativeDouble, this.minInt, this.maxLong, rangeDouble, this.notBlankString, this.customValidated);
  }

  public ValidationConfigImpl withNotBlankString(final String notBlankString) {
    return new ValidationConfigImpl(this.positiveInt, this.negativeDouble, this.minInt, this.maxLong, this.rangeDouble, notBlankString, this.customValidated);
  }

  public ValidationConfigImpl withCustomValidated(final String customValidated) {
    return new ValidationConfigImpl(this.positiveInt, this.negativeDouble, this.minInt, this.maxLong, this.rangeDouble, this.notBlankString, customValidated);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationConfigImpl that = (ValidationConfigImpl) o;
    if (!Objects.equals(this.positiveInt(), that.positiveInt())) return false;
    if (!Objects.equals(this.negativeDouble(), that.negativeDouble())) return false;
    if (!Objects.equals(this.minInt(), that.minInt())) return false;
    if (!Objects.equals(this.maxLong(), that.maxLong())) return false;
    if (!Objects.equals(this.rangeDouble(), that.rangeDouble())) return false;
    if (!Objects.equals(this.notBlankString(), that.notBlankString())) return false;
    if (!Objects.equals(this.customValidated(), that.customValidated())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.positiveInt(), this.negativeDouble(), this.minInt(), this.maxLong(), this.rangeDouble(), this.notBlankString(), this.customValidated());
  }
}
