package me.bristermitten.mittenlib.codegen.record

import com.palantir.javapoet.*
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import java.util.Locale
import javax.annotation.processing.Generated
import javax.lang.model.element.Modifier
import scala.jdk.CollectionConverters.*

object RecordGenerator:
  case class GeneratedRecord(
      recordImplName: ClassName,
      typeSpecBuilder: TypeSpec.Builder
  )

  def addAllArgsConstructor(
      constructor: RecordConstructorSpec,
      constructorTypeSpecBuilder: TypeSpec.Builder
  ): Unit =
    constructorTypeSpecBuilder.addMethod(
      MethodSpec
        .constructorBuilder()
        .addModifiers(Modifier.PUBLIC)
        .addParameters(constructor.fields.asScala.map { field =>
          ParameterSpec.builder(field.`type`, field.name).build()
        }.asJava)
        .addCode(
          constructor.fields.asScala
            .map { field =>
              s"this.${field.name} = ${field.name};"
            }
            .map(s => CodeBlock.of(s))
            .asJava
            .stream()
            .collect(CodeBlock.joining("\n"))
        )
        .build()
    )

  def addFieldAndGetter(
      field: RecordConstructorSpec.RecordFieldSpec,
      constructorTypeSpecBuilder: TypeSpec.Builder
  ): Unit =
    constructorTypeSpecBuilder.addField(
      field.`type`,
      field.name,
      Modifier.PRIVATE,
      Modifier.FINAL
    )

    constructorTypeSpecBuilder.addMethod(
      MethodSpec
        .methodBuilder(field.name)
        .addModifiers(Modifier.PUBLIC)
        .returns(field.`type`)
        .addStatement("return this.$N", field.name)
        .build()
    )

  def addWithMethod(
      constructorSpec: RecordConstructorSpec,
      field: RecordConstructorSpec.RecordFieldSpec,
      returnTypeName: ClassName,
      typeSpecBuilder: TypeSpec.Builder
  ): Unit =
    val capitalizedName =
      field.name.substring(0, 1).toUpperCase(Locale.ROOT) + field.name
        .substring(1)
    typeSpecBuilder.addMethod(
      MethodSpec
        .methodBuilder(s"with$capitalizedName")
        .addModifiers(Modifier.PUBLIC)
        .returns(returnTypeName)
        .addParameter(field.`type`, field.name)
        .addStatement(
          "return new $T($L)",
          returnTypeName,
          constructorSpec.fields.asScala
            .map { f =>
              if (f.name == field.name) {
                CodeBlock.of(field.name)
              } else {
                CodeBlock.of("this.$L", f.name)
              }
            }
            .asJava
            .stream()
            .collect(CodeBlock.joining(", "))
        )
        .build()
    )

  def addFactoryMethod(
      constructor: RecordConstructorSpec,
      returnTypeName: ClassName,
      typeSpecBuilder: TypeSpec.Builder
  ): Unit =
    typeSpecBuilder.addMethod(
      MethodSpec
        .methodBuilder(constructor.name)
        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
        .returns(returnTypeName)
        .addParameters(constructor.fields.asScala.map { field =>
          ParameterSpec.builder(field.`type`, field.name).build()
        }.asJava)
        .addStatement(
          "return new $L($L)",
          returnTypeName,
          constructor.fields.asScala
            .map(_.name)
            .map(s => CodeBlock.of(s))
            .asJava
            .stream()
            .collect(CodeBlock.joining(", "))
        )
        .build()
    )

  def generateBasicRecordTypeSpec(
      record: RecordSpecLike,
      extendSpec: Boolean
  ): RecordGenerator.GeneratedRecord =
    val recordImplName = record.name

    val typeSpecBuilder = TypeSpec.classBuilder(recordImplName)
    typeSpecBuilder.addModifiers(Modifier.PUBLIC, Modifier.FINAL)
    if (extendSpec) {
      typeSpecBuilder.addSuperinterface(record.source)
    }
    typeSpecBuilder.addAnnotation(
      AnnotationSpec
        .builder(classOf[me.bristermitten.mittenlib.codegen.GeneratedRecord])
        .addMember("source", "$T.class", record.source)
        .build()
    )

    typeSpecBuilder.addAnnotation(
      AnnotationSpec
        .builder(classOf[Generated])
        .addMember(
          "value",
          "$S",
          "me.bristermitten.mittenlib.codegen.BoilerplateGenerator"
        )
        .addMember(
          "comments",
          "$S",
          "Generated by MittenLib Annotation Processor"
        )
        .addMember(
          "date",
          "$S",
          ZonedDateTime
            .now(ZoneId.systemDefault())
            .format(DateTimeFormatter.ISO_INSTANT)
        )
        .build()
    )

    for (field <- record.constructor.fields.asScala) {
      addFieldAndGetter(field, typeSpecBuilder)
      addWithMethod(record.constructor, field, recordImplName, typeSpecBuilder)
    }
    addAllArgsConstructor(record.constructor, typeSpecBuilder)

    val bp = me.bristermitten.mittenlib.codegen.BoilerplateGenerator
    typeSpecBuilder.addMethod(
      bp.genToString(record.constructor, recordImplName)
    )
    typeSpecBuilder.addMethod(bp.genEquals(record.constructor, recordImplName))
    typeSpecBuilder.addMethod(bp.genHashCode(record.constructor))

    new RecordGenerator.GeneratedRecord(recordImplName, typeSpecBuilder)

class RecordGenerator:
  import RecordGenerator.*

  def generate(record: RecordSpec): JavaFile =
    val result = generateBasicRecordTypeSpec(record, true)
    addFactoryMethod(record.constructor, record.name, result.typeSpecBuilder)

    JavaFile
      .builder(
        result.recordImplName.packageName(),
        result.typeSpecBuilder.build()
      )
      .build()
